### ISSUE TITLE
只是用来创建api文档的吗，能不能连接数据库，把数据查询，或则编辑

### ISSUE THREAD

**Issue by rmtic** [Zhao-github/ApiAdmin#2]
只是用来创建api文档的吗，能不能连接数据库，把数据查询，或则编辑

**Comment by Zhao-github** [comment]
目前除了创建文档以外，我们还有：输入参数过滤，输出参数规整，融合三方接口，动态数据加载，二次开发友好等多个特性，当然大数据分析和API运营日报等相关功能也都在开发中
