### ISSUE TITLE
admin 模块 的模板在哪里？

### ISSUE THREAD

**Issue by westeast** [Zhao-github/ApiAdmin#3]
默认的admin用户是root密码是啥？

**Comment by westeast** [comment]
admin的登陆页面是是啥  index.php?s=/admin/Login/index  只是一个post接口呢?

**Comment by Zhao-github** [comment]
请访问：https://github.com/Zhao-github/ApiAdmin-WEB 获取后端模板

**Comment by Zhao-github** [comment]
@westeast 后台的默认用户名/密码是：root/123456

**Comment by westeast** [comment]
@Zhao-github 非常感谢~

**Comment by westeast** [comment]
模板编译后放在哪个目录里？
放入后是访问这个吗? index.php?s=/admin/Login/index   但这个接口我看你写的只能post 我用浏览器访问就是输入账号密码？

**Comment by Zhao-github** [comment]
具体的操作步骤和安装方式，请加入QQ群，关注公告获取帮助！
