### ISSUE TITLE
前端配置好了,跨域也没问题,登录的时候有问题

### ISSUE THREAD

**Issue by jonny77** [Zhao-github/ApiAdmin#4]
post地址i: https://api.apiadmin.org/admin/login/index
返回了这玩意儿:
{"code":1,"msg":"操作成功","data":{"Product":"ApiAdmin","Version":"v4.0","Company":"ApiAdmin开发维护团队","ToYou":"I'm glad to meet you（终于等到你！）"},"debug":[{"TpVersion":"5.1.39 LTS","Float":"17582429926"}]}
我访问不存在的路由也是返回这玩意儿.....

**Comment by Zhao-github** [comment]
后端需要生成后端路由
